packages:
  - playground
  - 'test/fixtures/*'

catalogs:
  dev:
    '@nuxt/devtools': 3.1.1
    '@nuxt/eslint-config': 1.11.0
    '@nuxt/module-builder': 1.0.2
    '@nuxtjs/color-mode': 4.0.0
    changelogen: ^0.6.2
    defu: ^6.1.4
    eslint: ^9.39.1
    nuxt: 4.2.1
    typescript: ~5.9.3
    vue-tsc: ^3.1.7
    destr: ^2.0.5
    yaml: ^2.8.2
  integrations:
    '@nuxt/content': ^3.9.0
    '@nuxt/kit': 4.2.1
    '@nuxt/schema': 4.2.1
    mermaid: ^11.12.2
  test:
    '@nuxt/test-utils': ^3.21.0
    playwright: ^1.57.0
    vitest: ^4.0.15
  types:
    '@types/node': ^24.10.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - unrs-resolver
