packages:
  - playground

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - unrs-resolver

catalogs:
  dev:
    nuxt: 4.2.1
    '@nuxtjs/color-mode': 4.0.0
    '@nuxt/devtools': 3.1.1
    '@nuxt/eslint-config': 1.11.0
    '@nuxt/module-builder': 1.0.2
    defu: ^6.1.4
    eslint: ^9.39.1
    changelogen: ^0.6.2
    typescript: ~5.9.3
    'vue-tsc': ^3.1.4

  test:
    '@nuxt/test-utils': 3.20.1
    vitest: ^4.0.14

  integrations:
    '@nuxt/kit': 4.2.1
    '@nuxt/schema': 4.2.1
    '@nuxt/content': 3.8.0
    mermaid: ^11.12.1

  types:
    '@types/node': latest
